- name: Check whether the deploy directory exists
  ansible.builtin.stat:
    path: "{{ deploy_backend_dir }}"
  register: deploy_backend_dir_stat

- name: Create the deploy directory
  ansible.builtin.file:
    path: "{{ deploy_backend_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  #become: true
  when: not deploy_backend_dir_stat.stat.exists

- name: Copy the Compose stack definition
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ deploy_backend_dir }}/compose.yml"
    mode: '0644'
  register: deploy_backend_compose_file
  