- name: precheck
  ansible.builtin.include_tasks: precheck.yml

- name: copy files
  ansible.builtin.include_tasks:
    copy_files.yml

- name: render templates
  ansible.builtin.include_tasks:
    render_templates.yml